apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "workspace.labels" . | nindent 4 }}
type: Opaque
data:
  ssh_host_ecdsa_key: "{{genPrivateKey "ecdsa" | b64enc}}"