name: Go package

on:
  push:
    tags: 
      - '*'
    branches:
      - 'main'

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: Build
        run: make bundle-linux-amd64
      - name: Bundle 
        uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: bundles/*
          retention-days: 2
  windows:
    name: windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: Build
        run: make bundle-windows-amd64
      - name: Bundle 
        uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: bundles/*
          retention-days: 2
  macos:
    name: macos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: Build
        run: make bundle-darwin-amd64
      - name: Bundle 
        uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: bundles/*
          retention-days: 2
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    needs: [macos, linux, windows]
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bundles
          path: bundles
      - uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["bundles/*"]'
      